#config file
#from can_assure_nov20.config import heart_beat_signals

user_send_signals = [
]

dbc_file_path = "/home/ee213681/Documents/EV_project_document/git/can_assure/can_assure/Files/full_frames.dbc"
Heart_beat_dbc = "Files/Mandatory/Heart_Beat.dbc"
timedelay = [1000, 2000, 3000]
sleeptime = 0
full_frame_dbc = "/home/ee213681/Documents/EV_project_document/git/can_assure/can_assure/Files/Mandatory/Heart_Beat.dbc"
type_h_file = "Files/Mandatory/types.h"

Peak_interface_name = "can0"
file_path = "vector_list.xlsx"
Vehicle_propID_type = {
}

GUI_title = "Can_AssuRE"
Display_size = "1400x1500"

#backend variables configurable
Testing_device = "Linux"   #"Linux"/"Windows"
Password = "Welcome@2024"
Bit_rate = "500000"
Drive_mode_prop_ID = "2140805f"

# validation on/off
Car_Service = "On" # "On"/"Off"
Kernal = "On" # "On"/"Off"
Cloud = "On"  # "On/Off"


#precheck values
pre_check_signal_value = 1  # Example value to send
pre_check_can_id = 0x310  # Example CAN ID
pre_check_signal_name = "OBC_Wakeup"  # Example Signal Name
pre_check_property_id = 0x80e5  # Not used directly but represents a meaningful parameter in your system

heart_beat_signals = [
    {
        'frame_name': 'Chrgr_STS_Info',
        'can_id': '0x310',
        'signals': {
            'Charger_Sts_Signal': 0,
            'Chrgr_Mode': 0,
            'Heartbeat_Fail_From_VCU': 0,
            'Heartbeat_Fail_From_BMS': 0,
            'OBC_Wakeup': 0,
            'PreChrg_Sts': 0,
        },
    },
    {
        'frame_name': 'Batt_Sts_Info',
        'can_id': '0x12d',
        'signals': {
            'Batt_Curr': 0,
            'Batt_Pack_SoC': 0,
            'Chrg_Vlt_limit': 0,
            'Chrgr_Mode_Request': 0,
            'Display_SoC': 99,
        },
    },
    {
        'frame_name': 'EHBL_OUTPUT_Data',
        'can_id': '0x4ce',
        'signals': {
            'EHBL_Sts': 1,
            'EHBL_Warningsafety': 0,
            'EHBL_BoltSts': 1,
            'EHBL_RotHandleBar': 0,
            'EHBL_Pwr_Supply_cutoff_flg': 0,
        },
    },
    {
        'frame_name': 'BMS_Parameter_1',
        'can_id': '0x12A',
        'signals': {
            'DisChrg_Contactor_state': 2,
            'Chrg_Contactor_state': 1,
            'PreChrg_Contactor_state': 0,
            'Batt_Pack_Bus_Vlt': 0,
            'BMS_Board_Temp': 0,
            'BMS_Mode': 0,
            'HVIL_OBC_Sts': 0,
            'HVIL_MCU_Sts': 0,
            'BMS_Regen_Inhibit': 0,
            'ASC_Prep_Flg': 0,
        },
    },
    {
        'frame_name': 'BMS_Parameter_2_Limit',
        'can_id': '0x12E',
        'signals': {
            'Effective_Batt_Temp': 0,
            'Delta_Temp': 0,
            'Delta_Vlt': 0,
            'Load_Vlt': 0,
            'Pack_Avail_Energy': 0,
        },
    },
    {
        'frame_name': 'BMS_Parameter_3',
        'can_id': '0x130',
        'signals': {
            'Pack_Internal_Resistance': 99,
            'Pack_SOH': 0,
            'Pack_Capacity': 0,
            'Total_Life_Cycle_Cnt': 0,
            'Pack_DOD': 0,
        },
    },
    {
        'frame_name': 'Batt_Temp',
        'can_id': '0x12F',
        'signals': {
            'Batt_Temp_1': 0,
            'Batt_Temp_2': 0,
            'Batt_Temp_3': 0,
            'Batt_Temp_4': 0,
            'Batt_Temp_5': 0,
            'Batt_Temp_6': 0,
            'Batt_Temp_Min': 0,
            'Batt_Temp_Max': 0,
        },
    },
    {
        'frame_name': 'MCU_Data_1',
        'can_id': '0x236',
        'signals': {
            'MCU_DC_Curr': 0,
            'MCU_Temp': 0,
            'Motor_Temp': 0,
            'Rotor_theta': 0,
        },
    },
    {
        'frame_name': 'MCU_Data_2',
        'can_id': '0x230',
        'signals': {
            'Rotor_Angle': 0,
            'Cruise_Control_Status': 0,
            'Hill_Hold_Sts': 0,
            'MCU_Ride_Modes': 0,
            'MCU_DC_vlt': 0,
            'MCU_12V_LV_monitor': 0,
            'MCU_12V_HV_Buck_monitor': 0,
            'Cruise_Set_Motor_RPM': 0,
            'Active_DisChrg': 0,
        },
    },
    {
        'frame_name': 'MCU_Data_3',
        'can_id': '0x231',
        'signals': {
            'R_Phase_Curr_MCU': 0,
            'Y_Phase_Curr_MCU': 0,
            'B_Phase_Curr_MCU': 0,
            'Regen_Min_Speed': 0,
        },
    },
    {
        'frame_name': 'MCU_Data_4',
        'can_id': '0x51',
        'signals': {
            'Motor_RPM': 0,
            'MCU_Torque_Request': 0,
            'Motor_Torque_Estimated': 0,
            'Motor_RPM_Val': 0,
            'MCU_Torque_Req_Val': 0,
            'Motor_Torque_Estimated_Val': 0,
            'MTC_Failure': 0,
            'MDTC_Failure': 0,
            'Alive_Cnt': 0,
            'CRC_Cnt': 0,
        },
    },
    {
        'frame_name': 'MCU_Data_5',
        'can_id': '0x233',
        'signals': {
            'MCU_MOSFET_Temp_R_phase': 0,
            'MCU_MOSFET_Temp_Y_Phase': 0,
            'MCU_MOSFET_Temp_B_Phase': 0,
            'MCU_PreChrg_Sts': 0,
            'MCU_12V_CutOFF_Flg': 0,
            'MCU_Machine_Mode': 0,
            'MCU_Speed_Limit': 0,
        },
    },
    {
        'frame_name': 'MCU_Data_6',
        'can_id': '0x235',
        'signals': {
            'Motor_Power': 0,
            'Regen_sts': 0,
            'OnAxix_3_3_Vlt': 0,
        },
    },
    {
        'frame_name': 'MCU_FLT_Data',
        'can_id': '0x341',
        'signals': {
            'Motor_OC_protect_U_phase': 0,
            'Motor_OC_protect_V_phase': 0,
            'Motor_OC_protect_W_phase': 0,
            'Mcu_Flt_Wrong_Offset_Flt': 0,
            'MCU_over_temp_warn': 0,
            'Motor_over_temp_warn': 0,
            'MCU_Unintended_Direction': 0,
            'Encoder_Fail': 0,
            'DCbus_UnderVlt': 0,
            'DCbus_OverVlt': 0,
            'DCbus_OverCurr': 0,
            'MCU_Over_speed_Flt': 0,
            'Mcu_Flt_DCBus_VltSnsr_STG': 0,
            'Mcu_Flt_DCBus_VoltgeSnsr_STB': 0,
            'MCU_Flt_KL30_Snsr_STG': 0,
            'MCU_Flt_KL30_Snsr_STB': 0,
            'Mcu_Flt_BoardTempSnsrSTG': 0,
            'Mcu_Flt_BoardTempSnsrSTB': 0,
            'Mcu_Flt_RphaseSTG': 0,
            'Mcu_Flt_RphaseSTB': 0,
            'Loss_of_VCU_Msg': 0,
            'LV_supplyOverVlt': 0,
            'LV_supplyUnderVlt': 0,
            'Mcu_Flt_YphaseSTG': 0,
            'Mcu_Flt_YphaseSTB': 0,
            'Mcu_Flt_BphaseSTG': 0,
            'Mcu_Flt_BphaseSTB': 0,
            'MCU_Flt_MachineTempSnsrSTB': 0,
            'MCU_Flt_MachineTempSnsrSTG': 0,
            'Mcu_Flt_DCCurrentSnsrSTG': 0,
            'Mcu_Flt_DCCurrentSnsrSTB': 0,
            'MCU_MOSFET_Low_Temp_Flt': 0,
            'MCU_Dio_DC_Over_Curr_Flt': 0,
            'MCU_dio_over_volt_sts': 0,
            'MCU_dio_over_curr_status': 0,
            'MCU_dio_phase_ctrl_sts': 0,
            'Mcu_Flt_MachineTemp_Low': 0,
            'Mcu_Flt_BoardTemp_Low': 0,
            'Mcu_Flt_Rotor_Stall': 0,
            'MCU_SBC_Fail_Sts': 0,
            'MCU_Flt_MOSFET_STG': 0,
            'MCU_Flt_MOSFET_STB': 0,
            'Throttle_ideal_per_Err': 0,
            'Mcu_Flt_BuckConverter_OV': 0,
            'Mcu_Flt_BuckConverter_STB': 0,
            'Mcu_Flt_BuckConverter_STG': 0,
            'Mcu_Flt_BuckConverter_UV': 0,
            'Mcu_Flt_NVM_Vlt_Notstable': 0,
            'Mcu_Flt_PhaseOffsetErr': 0,
            'MCU_NVM_Vlt_ChkSm_Mismatch': 0,
            'MOSFET_over_Temp_Warn': 0,
            'Motor_over_Temp_Err': 0,
            'MCU_over_Temp_Err': 0,
            'MOSFET_over_Temp_Err': 0,
            'MCU_Flt_On_Axis_Failure': 0,
            'MCU_Dio_Phase_Over_Curr_Sts': 0,
            'MCU_Phase_Curr_Sum_Flt': 0,
            'MCU_Unintended_Trq_Flt': 0,
            'MCU_GD_Int_b_Flt': 0,
            'MCU_GateDriver_Flt': 0,
            'MCU_SBC_Flt': 0,
            'MCU_OnAxis_Fail_Sts': 0,
            'MCU_GD_Fail_Sts': 0,
        },
    },
    {
        'frame_name': 'Batt_Limits',
        'can_id': '0x12C',
        'signals': {
            'Chrg_Curr_limit': 0,
            'DisChrg_Curr_limit': 0,
            'Regen_Curr_Limit': 0,
            'Time_to_Chrg_Hrs': 0,
            'Time_to_Chrg_Mins': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_1',
        'can_id': '0x500',
        'signals': {
            'Cell_Vlt_Cell_1': 0,
            'Cell_Vlt_Cell_2': 0,
            'Cell_Vlt_Cell_3': 0,
            'Cell_Vlt_Cell_4': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_2',
        'can_id': '0x501',
        'signals': {
            'Cell_Vlt_Cell_5': 0,
            'Cell_Vlt_Cell_6': 0,
            'Cell_Vlt_Cell_7': 0,
            'Cell_Vlt_Cell_8': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_3',
        'can_id': '0x502',
        'signals': {
            'Cell_Vlt_Cell_9': 0,
            'Cell_Vlt_Cell_10': 0,
            'Cell_Vlt_Cell_11': 0,
            'Cell_Vlt_Cell_12': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_4',
        'can_id': '0x503',
        'signals': {
            'Cell_Vlt_Cell_13': 0,
            'Cell_Vlt_Cell_14': 0,
            'Cell_Vlt_Cell_15': 0,
            'Cell_Vlt_Cell_16': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_5',
        'can_id': '0x505',
        'signals': {
            'Cell_Vlt_Cell_17': 0,
            'Cell_Vlt_Cell_18': 0,
            'Cell_Vlt_Cell_19': 0,
            'Cell_Vlt_Cell_20': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_6',
        'can_id': '0x506',
        'signals': {
            'Cell_Vlt_Cell_21': 0,
            'Cell_Vlt_Cell_22': 0,
            'Cell_Vlt_Cell_23': 0,
            'Cell_Vlt_Cell_24': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_7',
        'can_id': '0x507',
        'signals': {
            'Cell_Vlt_Cell_25': 0,
            'Cell_Vlt_Cell_26': 0,
            'Cell_Vlt_Cell_27': 0,
            'Cell_Vlt_Cell_28': 0,
        },
    },
    {
        'frame_name': 'BMS_Cell_Sts',
        'can_id': '0x508',
        'signals': {
            'BMS_BAL_Sts_Batt_Cell_1': 0,
            'BMS_BAL_Sts_Batt_Cell_2': 0,
            'BMS_BAL_Sts_Batt_Cell_3': 0,
            'BMS_BAL_Sts_Batt_Cell_4': 0,
            'BMS_BAL_Sts_Batt_Cell_5': 0,
            'BMS_BAL_Sts_Batt_Cell_6': 0,
            'BMS_BAL_Sts_Batt_Cell_7': 0,
            'BMS_BAL_Sts_Batt_Cell_8': 0,
            'BMS_BAL_Sts_Batt_Cell_9': 0,
            'BMS_BAL_Sts_Batt_Cell_10': 0,
            'BMS_BAL_Sts_Batt_Cell_11': 0,
            'BMS_BAL_Sts_Batt_Cell_12': 0,
            'BMS_BAL_Sts_Batt_Cell_13': 0,
            'BMS_BAL_Sts_Batt_Cell_14': 0,
            'BMS_BAL_Sts_Batt_Cell_15': 0,
            'BMS_BAL_Sts_Batt_Cell_16': 0,
            'BMS_BAL_Sts_Batt_Cell_17': 0,
            'BMS_BAL_Sts_Batt_Cell_18': 0,
            'BMS_BAL_Sts_Batt_Cell_19': 0,
            'BMS_BAL_Sts_Batt_Cell_20': 0,
            'BMS_BAL_Sts_Batt_Cell_21': 0,
            'BMS_BAL_Sts_Batt_Cell_22': 0,
            'BMS_BAL_Sts_Batt_Cell_23': 0,
            'BMS_BAL_Sts_Batt_Cell_24': 0,
            'BMS_BAL_Sts_Batt_Cell_25': 0,
            'BMS_BAL_Sts_Batt_Cell_26': 0,
            'BMS_BAL_Sts_Batt_Cell_27': 0,
            'BMS_BAL_Sts_Batt_Cell_28': 0,
            'BAL_Sts': 0,
            'BMS_Cell_Min_Vlt': 0,
            'BMS_Cell_Max_Vlt': 0,
        },
    },
    {
        'frame_name': 'BMS_Flt_1',
        'can_id': '0x509',
        'signals': {
            'BMS_Vlt_Snsr_Fail_Cell1': 0,
            'BMS_Vlt_Snsr_Fail_Cell2': 0,
            'BMS_Vlt_Snsr_Fail_Cell3': 0,
            'BMS_Vlt_Snsr_Fail_Cell4': 0,
            'BMS_Vlt_Snsr_Fail_Cell5': 0,
            'BMS_Vlt_Snsr_Fail_Cell6': 0,
            'BMS_Vlt_Snsr_Fail_Cell7': 0,
            'BMS_Vlt_Snsr_Fail_Cell8': 0,
            'BMS_Vlt_Snsr_Fail_Cell9': 0,
            'BMS_Vlt_Snsr_Fail_Cell10': 0,
            'BMS_Vlt_Snsr_Fail_Cell11': 0,
            'BMS_Vlt_Snsr_Fail_Cell12': 0,
            'BMS_Vlt_Snsr_Fail_Cell13': 0,
            'BMS_Vlt_Snsr_Fail_Cell14': 0,
            'BMS_Vlt_Snsr_Fail_Cell15': 0,
            'BMS_Vlt_Snsr_Fail_Cell16': 0,
            'BMS_Vlt_Snsr_Fail_Cell17': 0,
            'BMS_Vlt_Snsr_Fail_Cell18': 0,
            'BMS_Vlt_Snsr_Fail_Cell19': 0,
            'BMS_Vlt_Snsr_Fail_Cell20': 0,
            'BMS_Vlt_Snsr_Fail_Cell21': 0,
            'BMS_Vlt_Snsr_Fail_Cell22': 0,
            'BMS_Vlt_Snsr_Fail_Cell23': 0,
            'BMS_Vlt_Snsr_Fail_Cell24': 0,
            'BMS_Vlt_Snsr_Fail_Cell25': 0,
            'BMS_Vlt_Snsr_Fail_Cell26': 0,
            'BMS_Vlt_Snsr_Fail_Cell27': 0,
            'BMS_Vlt_Snsr_Fail_Cell28': 0,
            'BMS_BattPack_Temp1_Snsr_Fail': 0,
            'BMS_BattPack_Temp2_Snsr_Fail': 0,
            'BMS_BattPack_Temp3_Snsr_Fail': 0,
            'BMS_BattPack_Temp4_Snsr_Fail': 0,
            'BMS_BattPack_Temp5_Snsr_Fail': 0,
            'BMS_BattPack_Temp6_Snsr_Fail': 0,
        },
    },
    {
        'frame_name': 'BMS_Flt_2',
        'can_id': '0x50A',
        'signals': {
            'BMS_Low_Temp_Chrg_Warn_info': 0,
            'BMS_Low_Temp_during_Chrg_Err': 0,
            'BMS_Low_Temp_during_Drv_Warn': 0,
            'BMS_Low_Temp_during_Drv_Err': 0,
            'BMS_Under_Vlt_Warn_Info': 0,
            'BMS_Under_Vlt_Err': 0,
            'BMS_LPDCDC_CutOFF': 0,
            'BMS_Over_Vlt_Chrg_Err': 0,
            'BMS_Over_Temp_Chrg_Warn_Info': 0,
            'BMS_Over_Temp_Chrg_Err': 0,
            'BMS_Over_Temp_Drv_Warn_Info': 0,
            'BMS_Over_Temp_Drv_Err': 0,
            'BMS_DisChrg_Over_Curr': 0,
            'BMS_Over_Curr_Chrg_Err': 0,
            'BMS_PreChrg_Fail': 0,
            'BMS_PreChrg_No_Load_Detected': 0,
            'BMS_PDU_Lock_HW': 0,
            'BMS_Insulation_Monitor_Err': 0,
            'BMS_Cell_Temp_Imbalance': 0,
            'BMS_Thermal_Runaway': 0,
            'VCU_CAN_Heartbeat_Err': 0,
            'OBC_CAN_Heartbeat_Err': 0,
            'PreChrg_Relay_Weld': 0,
            'Pos_Contactor_Weld': 0,
            'HPDCDC_OP_FAIL': 0,
            'LOW_SOC_WARN': 0,
            'LOW_SOC': 0,
            'AFE_SPI_Heartbeat_Fail_Err': 0,
            'AFE_ISO_Fail_Err': 0,
            'Pack_Monitor_Fail': 0,
            'AFE1_Fail': 0,
            'LPDCDC_OP_FAIL': 0,
            'BMS_Short_Ckt_Detect_Err': 0,
            'BMS_PDU_Fail': 0,
            'BMS_Chrgr_Fuse_Fail': 0,
            'BMS_Dischrg_Fuse_Fail': 0,
            'BMS_Curr_Snsr_Fail_Open_Ckt': 0,
            'BMS_Curr_Snsr_Fail_Shrt_Ckt': 0,
            'HVIL_MCU_Err': 0,
            'HVIL_OBC_Err': 0,
            'BMS_LP_DCDC_Output_Shrt_Ckt': 0,
            'BMS_Gas_Snsr_Err': 0,
            'BMS_Pressure_Snsr_Err': 0,
            'Pyro_Fuse_Sts': 0,
            'Fire_Ext_Sts': 0,
            'Low_SOC_Warn_15': 0,
            'BMS_UV_Permnt_Flt': 0,
            'BMS_OV_Permnt_Flt': 0,
            'BMS_Prechrg_Overload': 0,
            'BMS_Internal_Fault': 0,
            'BMS_Vlt_Imbalance_flt': 0,
            'BMS_LP_DCDC_Ovload_flt': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_4',
        'can_id': '0x503',
        'signals': {
            'Cell_Vlt_Cell_13': 0,
            'Cell_Vlt_Cell_14': 0,
            'Cell_Vlt_Cell_15': 0,
            'Cell_Vlt_Cell_16': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_5',
        'can_id': '0x505',
        'signals': {
            'Cell_Vlt_Cell_17': 0,
            'Cell_Vlt_Cell_18': 0,
            'Cell_Vlt_Cell_19': 0,
            'Cell_Vlt_Cell_20': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_6',
        'can_id': '0x506',
        'signals': {
            'Cell_Vlt_Cell_21': 0,
            'Cell_Vlt_Cell_22': 0,
            'Cell_Vlt_Cell_23': 0,
            'Cell_Vlt_Cell_24': 0,
        },
    },
    {
        'frame_name': 'BMS_CELL_VLT_7',
        'can_id': '0x507',
        'signals': {
            'Cell_Vlt_Cell_25': 0,
            'Cell_Vlt_Cell_26': 0,
            'Cell_Vlt_Cell_27': 0,
            'Cell_Vlt_Cell_28': 0,
        },
    },
    {
        'frame_name': 'BMS_Cell_Sts',
        'can_id': '0x508',
        'signals': {
            'BMS_BAL_Sts_Batt_Cell_1': 0,
            'BMS_BAL_Sts_Batt_Cell_2': 0,
            'BMS_BAL_Sts_Batt_Cell_3': 0,
            'BMS_BAL_Sts_Batt_Cell_4': 0,
            'BMS_BAL_Sts_Batt_Cell_5': 0,
            'BMS_BAL_Sts_Batt_Cell_6': 0,
            'BMS_BAL_Sts_Batt_Cell_7': 0,
            'BMS_BAL_Sts_Batt_Cell_8': 0,
            'BMS_BAL_Sts_Batt_Cell_9': 0,
            'BMS_BAL_Sts_Batt_Cell_10': 0,
            'BMS_BAL_Sts_Batt_Cell_11': 0,
            'BMS_BAL_Sts_Batt_Cell_12': 0,
            'BMS_BAL_Sts_Batt_Cell_13': 0,
            'BMS_BAL_Sts_Batt_Cell_14': 0,
            'BMS_BAL_Sts_Batt_Cell_15': 0,
            'BMS_BAL_Sts_Batt_Cell_16': 0,
            'BMS_BAL_Sts_Batt_Cell_17': 0,
            'BMS_BAL_Sts_Batt_Cell_18': 0,
            'BMS_BAL_Sts_Batt_Cell_19': 0,
            'BMS_BAL_Sts_Batt_Cell_20': 0,
            'BMS_BAL_Sts_Batt_Cell_21': 0,
            'BMS_BAL_Sts_Batt_Cell_22': 0,
            'BMS_BAL_Sts_Batt_Cell_23': 0,
            'BMS_BAL_Sts_Batt_Cell_24': 0,
            'BMS_BAL_Sts_Batt_Cell_25': 0,
            'BMS_BAL_Sts_Batt_Cell_26': 0,
            'BMS_BAL_Sts_Batt_Cell_27': 0,
            'BMS_BAL_Sts_Batt_Cell_28': 0,
            'BAL_Sts': 0,
            'BMS_Cell_Min_Vlt': 0,
            'BMS_Cell_Max_Vlt': 0,
        },
    },
    {
        'frame_name': 'BMS_Flt_1',
        'can_id': '0x509',
        'signals': {
            'BMS_Vlt_Snsr_Fail_Cell1': 0,
            'BMS_Vlt_Snsr_Fail_Cell2': 0,
            'BMS_Vlt_Snsr_Fail_Cell3': 0,
            'BMS_Vlt_Snsr_Fail_Cell4': 0,
            'BMS_Vlt_Snsr_Fail_Cell5': 0,
            'BMS_Vlt_Snsr_Fail_Cell6': 0,
            'BMS_Vlt_Snsr_Fail_Cell7': 0,
            'BMS_Vlt_Snsr_Fail_Cell8': 0,
            'BMS_Vlt_Snsr_Fail_Cell9': 0,
            'BMS_Vlt_Snsr_Fail_Cell10': 0,
            'BMS_Vlt_Snsr_Fail_Cell11': 0,
            'BMS_Vlt_Snsr_Fail_Cell12': 0,
            'BMS_Vlt_Snsr_Fail_Cell13': 0,
            'BMS_Vlt_Snsr_Fail_Cell14': 0,
            'BMS_Vlt_Snsr_Fail_Cell15': 0,
            'BMS_Vlt_Snsr_Fail_Cell16': 0,
            'BMS_Vlt_Snsr_Fail_Cell17': 0,
            'BMS_Vlt_Snsr_Fail_Cell18': 0,
            'BMS_Vlt_Snsr_Fail_Cell19': 0,
            'BMS_Vlt_Snsr_Fail_Cell20': 0,
            'BMS_Vlt_Snsr_Fail_Cell21': 0,
            'BMS_Vlt_Snsr_Fail_Cell22': 0,
            'BMS_Vlt_Snsr_Fail_Cell23': 0,
            'BMS_Vlt_Snsr_Fail_Cell24': 0,
            'BMS_Vlt_Snsr_Fail_Cell25': 0,
            'BMS_Vlt_Snsr_Fail_Cell26': 0,
            'BMS_Vlt_Snsr_Fail_Cell27': 0,
            'BMS_Vlt_Snsr_Fail_Cell28': 0,
            'BMS_BattPack_Temp1_Snsr_Fail': 0,
            'BMS_BattPack_Temp2_Snsr_Fail': 0,
            'BMS_BattPack_Temp3_Snsr_Fail': 0,
            'BMS_BattPack_Temp4_Snsr_Fail': 0,
            'BMS_BattPack_Temp5_Snsr_Fail': 0,
            'BMS_BattPack_Temp6_Snsr_Fail': 0,
        },
    },
    {
        'frame_name': 'BMS_Flt_2',
        'can_id': '0x50A',
        'signals': {
            'BMS_Low_Temp_Chrg_Warn_info': 0,
            'BMS_Low_Temp_during_Chrg_Err': 0,
            'BMS_Low_Temp_during_Drv_Warn': 0,
            'BMS_Low_Temp_during_Drv_Err': 0,
            'BMS_Under_Vlt_Warn_Info': 0,
            'BMS_Under_Vlt_Err': 0,
            'BMS_LPDCDC_CutOFF': 0,
            'BMS_Over_Vlt_Chrg_Err': 0,
            'BMS_Over_Temp_Chrg_Warn_Info': 0,
            'BMS_Over_Temp_Chrg_Err': 0,
            'BMS_Over_Temp_Drv_Warn_Info': 0,
            'BMS_Over_Temp_Drv_Err': 0,
            'BMS_DisChrg_Over_Curr': 0,
            'BMS_Over_Curr_Chrg_Err': 0,
            'BMS_PreChrg_Fail': 0,
            'BMS_PreChrg_No_Load_Detected': 0,
            'BMS_PDU_Lock_HW': 0,
            'BMS_Insulation_Monitor_Err': 0,
            'BMS_Cell_Temp_Imbalance': 0,
            'BMS_Thermal_Runaway': 0,
            'VCU_CAN_Heartbeat_Err': 0,
            'OBC_CAN_Heartbeat_Err': 0,
            'PreChrg_Relay_Weld': 0,
            'Pos_Contactor_Weld': 0,
            'HPDCDC_OP_FAIL': 0,
            'LOW_SOC_WARN': 0,
            'LOW_SOC': 0,
            'AFE_SPI_Heartbeat_Fail_Err': 0,
            'AFE_ISO_Fail_Err': 0,
            'Pack_Monitor_Fail': 0,
            'AFE1_Fail': 0,
            'LPDCDC_OP_FAIL': 0,
            'BMS_Short_Ckt_Detect_Err': 0,
            'BMS_PDU_Fail': 0,
            'BMS_Chrgr_Fuse_Fail': 0,
            'BMS_Dischrg_Fuse_Fail': 0,
            'BMS_Curr_Snsr_Fail_Open_Ckt': 0,
            'BMS_Curr_Snsr_Fail_Shrt_Ckt': 0,
            'HVIL_MCU_Err': 0,
            'HVIL_OBC_Err': 0,
            'BMS_LP_DCDC_Output_Shrt_Ckt': 0,
            'BMS_Gas_Snsr_Err': 0,
            'BMS_Pressure_Snsr_Err': 0,
            'Pyro_Fuse_Sts': 0,
            'Fire_Ext_Sts': 0,
            'Low_SOC_Warn_15': 0,
            'BMS_UV_Permnt_Flt': 0,
            'BMS_OV_Permnt_Flt': 0,
            'BMS_Prechrg_Overload': 0,
            'BMS_Internal_Fault': 0,
            'BMS_Vlt_Imbalance_flt': 0,
            'BMS_LP_DCDC_Ovload_flt': 0,
        },
    }
]



